### ISSUE TITLE
# 99%的前端初学者都会搞混的offset...

### ISSUE THREAD

**Issue by Jaycexx** [329530588/329530588.github.io#3]
前端学习过程中会经常遇到offsetX、offsetLeft、clientX之类的概念，如果没有作系统性的总结，就很容易搞混。本文主要基于MDN的定义和自身的实践总结，其中有兼容性问题的属性会用`()`在后面注明。

话休饶舌，下面让小生来给大家梳理一下。

与offset相关的属性可以分为两类：
## mouse event的属性
+ pageX： 返回页面左上角的相对距离，包括滚动距离(IE9+)    
+ **offsetX**： 这个属性很容易混淆，所以加粗了。网上有的博客说这个属性与pageX表现一样，其实是错误的，正确的说是相对于父容器的偏移，与下文的offsetTop/Height类似(IE6+)    
+ screenX： 返回距离屏幕左上角的距离    
+ clientX： 距离浏览器可视区域左上角的距离(IE6+)        

为了直观地看出区别，小生画了一张图：
![untitled](https://user-images.githubusercontent.com/5203240/28497992-cf112152-6fc6-11e7-8074-b6f219e06e62.png)

## HTMLelement的属性
+ offsetTop： 相对offsetParent元素的top偏移    
+ offsetLeft： 相对offsetParent元素的left偏移(IE Edge支持) 
+ offsetParent： 相对其定位的父元素  (IE Edge支持)  
+ offsetHeight： 渲染时的高度(IE Edge支持)    
+ offsetWidth： 渲染时的宽度(IE Edge支持)

文字有点绕，放个demo直观点

live demo: https://jsfiddle.net/fokess/wats4cse/embed/js,html,css,result/dark/

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
<div id="p1">
  <div id="p2">
    <div id="content">
      lalala
    </div>
  </div>
</div>
</body>
</html>
```

```css
#content {
  background: green;
  position: absolute;
  top: 1000px;
}
#p1 {
  background: black;
  position: relative;
}
#p2 {
  position: relative;
  background: white;
  left: 100px;
  top: 100px;
}
```
```javascript
var target = document.getElementById('content');
console.log('offsetHeight:', target.offsetHeight);
console.log('offsetWidth:', target.offsetWidth);
console.log('offsetParent:', target.offsetParent);
console.log('offsetTop:', target.offsetTop);
console.log('offsetLeft:', target.offsetLeft);
```
当把p2的`position:relative`注释掉之后，offsetParent就变成p1了。
